version: '3'

services:
  app1:
    image: alpine:latest
    entrypoint: ping host.docker.internal
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}

  app2:
    image: alpine:latest
    entrypoint: ping host.docker.internal
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}
